// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nimbo.Wms.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nimbo.Wms.Migrations
{
    [DbContext(typeof(NimboWmsDbContext))]
    [Migration("20260401142800_UpdateMaxLengthConstraints")]
    partial class UpdateMaxLengthConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nimbo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Adjustment.AdjustmentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReasonText")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("WarehouseId");

                    b.ToTable("adjustment_documents", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Adjustment.AdjustmentDocumentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Delta", "Nimbo.Wms.Domain.Entities.Documents.Adjustment.AdjustmentDocumentLine.Delta#QuantityDelta", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("delta_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("delta_amount");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId", "ItemId", "LocationId");

                    b.ToTable("adjustment_document_lines", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.CycleCount.CycleCountDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("WarehouseId");

                    b.ToTable("cycle_count_documents", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.CycleCount.CycleCountDocumentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ActualQuantity", "Nimbo.Wms.Domain.Entities.Documents.CycleCount.CycleCountDocumentLine.ActualQuantity#Quantity", b1 =>
                        {
                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("actual_quantity_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("actual_quantity_amount");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quantity", "Nimbo.Wms.Domain.Entities.Documents.CycleCount.CycleCountDocumentLine.Quantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("expected_quantity_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("expected_quantity_amount");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId", "ItemId", "LocationId")
                        .IsUnique();

                    b.ToTable("cycle_count_document_lines", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Receiving.ReceivingDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("receiving_documents", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Receiving.ReceivingDocumentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ExpectedQuantity", "Nimbo.Wms.Domain.Entities.Documents.Receiving.ReceivingDocumentLine.ExpectedQuantity#Quantity", b1 =>
                        {
                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("expected_quantity_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("expected_quantity_amount");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quantity", "Nimbo.Wms.Domain.Entities.Documents.Receiving.ReceivingDocumentLine.Quantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("quantity_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("quantity_amount");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ItemId");

                    b.HasIndex("DocumentId", "ItemId");

                    b.ToTable("receiving_document_lines", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Relocation.RelocationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("WarehouseId");

                    b.ToTable("relocation_documents", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Relocation.RelocationDocumentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("From")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("To")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quantity", "Nimbo.Wms.Domain.Entities.Documents.Relocation.RelocationDocumentLine.Quantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("quantity_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("quantity_amount");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("From");

                    b.HasIndex("ItemId");

                    b.HasIndex("To");

                    b.HasIndex("DocumentId", "ItemId");

                    b.HasIndex("DocumentId", "ItemId", "From", "To");

                    b.ToTable("relocation_document_lines", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Shipment.ShipmentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("WarehouseId");

                    b.ToTable("shipment_documents", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Shipment.ShipmentDocumentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quantity", "Nimbo.Wms.Domain.Entities.Documents.Shipment.ShipmentDocumentLine.Quantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("requested_quantity_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("requested_quantity_amount");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ItemId");

                    b.HasIndex("DocumentId", "ItemId");

                    b.ToTable("shipment_document_lines", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Shipment.ShipmentPickLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromLocation")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quantity", "Nimbo.Wms.Domain.Entities.Documents.Shipment.ShipmentPickLine.Quantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("picked_quantity_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("picked_quantity_amount");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId", "ItemId", "FromLocation");

                    b.ToTable("shipment_pick_lines", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Ledger.StockLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceDocumentLineId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BalanceAfter", "Nimbo.Wms.Domain.Entities.Ledger.StockLedgerEntry.BalanceAfter#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("balance_after_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("balance_after_amount");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "QuantityDelta", "Nimbo.Wms.Domain.Entities.Ledger.StockLedgerEntry.QuantityDelta#QuantityDelta", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("quantity_delta_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("quantity_delta_amount");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("InventoryItemId", "OccurredAt");

                    b.HasIndex("ItemId", "LocationId");

                    b.ToTable("stock_ledger_entries", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("customers", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("BaseUomCode")
                        .HasColumnType("integer");

                    b.Property<string>("InternalSku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal?>("VolumeM3")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InternalSku")
                        .IsUnique();

                    b.ToTable("items", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Email")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("suppliers", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.SupplierItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DefaultPurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MinOrderQty")
                        .HasColumnType("integer");

                    b.Property<string>("PurchaseUomCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SupplierBarcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierSku")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("UnitsPerPurchaseUom")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SupplierId", "ItemId");

                    b.ToTable("supplier_items", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Stock.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ManufacturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("SupplierId");

                    b.HasIndex("ItemId", "BatchNumber")
                        .IsUnique();

                    b.ToTable("batches", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Stock.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("numeric(18, 4)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quantity", "Nimbo.Wms.Domain.Entities.Stock.InventoryItem.Quantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("quantity_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("quantity_amount");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("LocationId");

                    b.HasIndex("Status");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ItemId", "WarehouseId", "LocationId");

                    b.ToTable("inventory_items", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Topology.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Aisle")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPickingLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReceivingLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShippingLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSingleItemOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("MaxVolumeM3")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("Position")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Rack")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ZoneId");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique();

                    b.ToTable("locations", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Topology.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("warehouses", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Topology.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsDamagedArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsQuarantine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MaxVolumeM3")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique();

                    b.ToTable("zones", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Adjustment.AdjustmentDocumentLine", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.Documents.Adjustment.AdjustmentDocument", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.CycleCount.CycleCountDocumentLine", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.Documents.CycleCount.CycleCountDocument", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Receiving.ReceivingDocumentLine", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.Documents.Receiving.ReceivingDocument", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Relocation.RelocationDocumentLine", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.Documents.Relocation.RelocationDocument", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.Topology.Location", null)
                        .WithMany()
                        .HasForeignKey("From")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.Topology.Location", null)
                        .WithMany()
                        .HasForeignKey("To")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Shipment.ShipmentDocumentLine", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.Documents.Shipment.ShipmentDocument", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Shipment.ShipmentPickLine", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.Documents.Shipment.ShipmentDocument", null)
                        .WithMany("PickLines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.SupplierItem", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Supplier", null)
                        .WithMany("Items")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Stock.Batch", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Stock.InventoryItem", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.Stock.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.Topology.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.Topology.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Topology.Location", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.Topology.Warehouse", null)
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Topology.Zone", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.Topology.Warehouse", null)
                        .WithMany("Zones")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Adjustment.AdjustmentDocument", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.CycleCount.CycleCountDocument", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Receiving.ReceivingDocument", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Relocation.RelocationDocument", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Documents.Shipment.ShipmentDocument", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("PickLines");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.Supplier", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Topology.Warehouse", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
