// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nimbo.Wms.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nimbo.Wms.Migrations
{
    [DbContext(typeof(NimboWmsDbContext))]
    [Migration("20260108101605_Add_InboundDelivery_Configuration")]
    partial class Add_InboundDelivery_Configuration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nimbo")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nimbo.Wms.Domain.Documents.Audit.InventoryCount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid[]>("_locationScope")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("location_scope");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("WarehouseId");

                    b.ToTable("inventory_counts", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Documents.Audit.InventoryCountLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryCountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryCountId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.ToTable("inventory_count_lines", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Documents.Inbound.InboundDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("inbound_deliveries", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Documents.Inbound.InboundDeliveryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("ExpectedQuantity")
                        .HasColumnType("numeric(8)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InboundDeliveryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ReceivedQuantity")
                        .HasColumnType("numeric(8)");

                    b.Property<int>("Uom")
                        .HasMaxLength(16)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InboundDeliveryId");

                    b.HasIndex("ItemId");

                    b.ToTable("inbound_delivery_lines", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Email")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("customers", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("BaseUomCode")
                        .HasColumnType("integer");

                    b.Property<string>("InternalSku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal?>("VolumeM3")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InternalSku")
                        .IsUnique();

                    b.ToTable("items", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Email")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("suppliers", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.SupplierItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DefaultPurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MinOrderQty")
                        .HasColumnType("integer");

                    b.Property<string>("PurchaseUomCode")
                        .HasColumnType("text");

                    b.Property<string>("SupplierBarcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierSku")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("UnitsPerPurchaseUom")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SupplierId");

                    b.ToTable("supplier_items", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Movements.InternalTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("internal_transfers", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Stock.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ManufacturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("SupplierId");

                    b.HasIndex("ItemId", "BatchNumber")
                        .IsUnique();

                    b.ToTable("batches", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Stock.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("numeric(18, 4)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("LocationId");

                    b.HasIndex("Status");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ItemId", "WarehouseId", "LocationId");

                    b.ToTable("inventory_items", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.WarehouseData.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Aisle")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPickingLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReceivingLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShippingLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSingleItemOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("MaxVolumeM3")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("Position")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Rack")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ZoneId");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique();

                    b.ToTable("locations", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.WarehouseData.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("warehouses", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.WarehouseData.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsDamagedArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsQuarantine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MaxVolumeM3")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique();

                    b.ToTable("zones", "nimbo");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Documents.Audit.InventoryCountLine", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Documents.Audit.InventoryCount", null)
                        .WithMany("Lines")
                        .HasForeignKey("InventoryCountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nimbo.Wms.Domain.ValueObject.Quantity", "CountedQuantity", b1 =>
                        {
                            b1.Property<Guid>("InventoryCountLineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("counted_qty_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("counted_qty_amount");

                            b1.HasKey("InventoryCountLineId");

                            b1.ToTable("inventory_count_lines", "nimbo");

                            b1.WithOwner()
                                .HasForeignKey("InventoryCountLineId");
                        });

                    b.OwnsOne("Nimbo.Wms.Domain.ValueObject.Quantity", "SystemQuantity", b1 =>
                        {
                            b1.Property<Guid>("InventoryCountLineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("system_qty_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("system_qty_amount");

                            b1.HasKey("InventoryCountLineId");

                            b1.ToTable("inventory_count_lines", "nimbo");

                            b1.WithOwner()
                                .HasForeignKey("InventoryCountLineId");
                        });

                    b.Navigation("CountedQuantity");

                    b.Navigation("SystemQuantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Documents.Inbound.InboundDeliveryLine", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Documents.Inbound.InboundDelivery", null)
                        .WithMany("Lines")
                        .HasForeignKey("InboundDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.MasterData.SupplierItem", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Movements.InternalTransfer", b =>
                {
                    b.OwnsOne("Nimbo.Wms.Domain.ValueObject.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("InternalTransferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("quantity_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("quantity_amount");

                            b1.HasKey("InternalTransferId");

                            b1.ToTable("internal_transfers", "nimbo");

                            b1.WithOwner()
                                .HasForeignKey("InternalTransferId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Stock.Batch", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.Stock.InventoryItem", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.Stock.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nimbo.Wms.Domain.Entities.MasterData.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.WarehouseData.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.WarehouseData.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Nimbo.Wms.Domain.ValueObject.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("quantity_uom");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18, 3)")
                                .HasColumnName("quantity_amount");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("inventory_items", "nimbo");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.WarehouseData.Location", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.WarehouseData.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nimbo.Wms.Domain.Entities.WarehouseData.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Entities.WarehouseData.Zone", b =>
                {
                    b.HasOne("Nimbo.Wms.Domain.Entities.WarehouseData.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Documents.Audit.InventoryCount", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Nimbo.Wms.Domain.Documents.Inbound.InboundDelivery", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
